apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-rabbitmq
  template:
    metadata:
      labels:
        app: calendar-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          ports:
            - containerPort: 5672  # RabbitMQ
            - containerPort: 15672 # Management UI

---
apiVersion: v1
kind: Service
metadata:
  name: calendar-rabbitmq
spec:
  selector:
    app: calendar-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbitmq-management
