apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-app
  template:
    metadata:
      labels:
        app: calendar-app
    spec:
      containers:
        - name: calendar
          image: thejubadze/calendar:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-app
spec:
  selector:
    app: calendar-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8081
      targetPort: 8081
      name: grpc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calendar-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: calendar.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calendar-app
                port:
                  number: 8080
