apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-db
  template:
    metadata:
      labels:
        app: calendar-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/calendar_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: calendar-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calendar-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "calendar"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: calendar-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
