apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.amqpName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.amqpName }}
  template:
    metadata:
      labels:
        app: {{ .Values.amqpName }}
    spec:
      containers:
        - name: {{ .Values.amqpName }}
          image: {{ .Values.amqpName }}:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretsName }}
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretsName }}
                  key: RABBITMQ_DEFAULT_PASS
          ports:
            - containerPort: 5672  # RabbitMQ
            - containerPort: 15672 # Management UI
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.amqpName }}
spec:
  selector:
    app: {{ .Values.amqpName }}
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: {{ .Values.amqpName }}
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: {{ .Values.amqpName }}-management
