apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretsName }}
type: Opaque
data:
  POSTGRES_USER: cm9vdA== # base64 "root"
  POSTGRES_PASSWORD: MTIz # base64 "123"
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q= # base64 "guest"
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q= # base64 "guest"
