//go:build bench
// +build bench

package hw10programoptimization

import (
	"archive/zip"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

const (
	myMb          uint64 = 1 << 20
	myMemoryLimit uint64 = 11 * myMb

	myTimeLimit = 15 * time.Millisecond
)

// go test -v -count=1 -timeout=30s -tags bench .
func TestGetDomainStat_Time_And_Memory_My(t *testing.T) {
	bench := func(b *testing.B) {
		b.Helper()
		b.StopTimer()

		r, err := zip.OpenReader("testdata/new_users.zip")
		require.NoError(t, err)
		defer r.Close()

		require.Equal(t, 1, len(r.File))

		data, err := r.File[0].Open()
		require.NoError(t, err)

		b.StartTimer()
		stat, err := GetDomainStat(data, "com")
		b.StopTimer()
		require.NoError(t, err)

		require.Equal(t, myExpectedBizStat, stat)
	}

	result := testing.Benchmark(bench)
	mem := result.MemBytes
	t.Logf("time used: %s / %s", result.T, myTimeLimit)
	t.Logf("memory used: %dMb / %dMb", mem/myMb, myMemoryLimit/myMb)

	require.Less(t, int64(result.T), int64(myTimeLimit), "the program is too slow")
	require.Less(t, mem, myMemoryLimit, "the program is too greedy")
}

var myExpectedBizStat = DomainStat{
	"gmail.com":              187,
	"hotmail.com":            153,
	"yahoo.com":              164,
	"robinson.com":           7,
	"smith.com":              6,
	"hernandez.com":          3,
	"johnson.com":            3,
	"parks.com":              3,
	"taylor.com":             3,
	"brown.com":              2,
	"bennett.com":            2,
	"calhoun.com":            2,
	"davis.com":              2,
	"edwards.com":            2,
	"fields.com":             2,
	"franklin.com":           2,
	"hampton.com":            2,
	"harris.com":             2,
	"lopez.com":              2,
	"nguyen.com":             2,
	"orr.com":                2,
	"patterson.com":          2,
	"reyes.com":              2,
	"roberts.com":            2,
	"robertson.com":          2,
	"rodriguez.com":          2,
	"stanley.com":            2,
	"stewart.com":            2,
	"thomas.com":             2,
	"weaver.com":             2,
	"wells.com":              2,
	"wilson.com":             2,
	"adams-bauer.com":        1,
	"adams.com":              1,
	"aguirre.com":            1,
	"allen.com":              1,
	"anderson-thompson.com":  1,
	"anderson.com":           1,
	"andrews.com":            1,
	"arias.com":              1,
	"atkins.com":             1,
	"bailey.com":             1,
	"baker.com":              1,
	"ballard.com":            1,
	"barker-patterson.com":   1,
	"barron.com":             1,
	"barton-aguirre.com":     1,
	"bates-pacheco.com":      1,
	"baxter.com":             1,
	"bell.com":               1,
	"benson.com":             1,
	"bishop-marsh.com":       1,
	"blake.com":              1,
	"bonilla.com":            1,
	"boone-james.com":        1,
	"bowers-carr.com":        1,
	"brewer.com":             1,
	"brooks.com":             1,
	"buck.com":               1,
	"buckley-adams.com":      1,
	"burke-jones.com":        1,
	"burke.com":              1,
	"butler-scott.com":       1,
	"cabrera.com":            1,
	"carlson-barrett.com":    1,
	"carpenter-stone.com":    1,
	"carpenter.com":          1,
	"chase.com":              1,
	"chavez.com":             1,
	"cherry.com":             1,
	"clark-zamora.com":       1,
	"collins-ramirez.com":    1,
	"conway.com":             1,
	"craig.com":              1,
	"crawford.com":           1,
	"cummings.com":           1,
	"curtis.com":             1,
	"daniels-daniel.com":     1,
	"daniels-daniels.com":    1,
	"davies-valentine.com":   1,
	"davis-jenkins.com":      1,
	"dennis-ford.com":        1,
	"dillon-ortiz.com":       1,
	"drake.com":              1,
	"duran-brown.com":        1,
	"edwards-ford.com":       1,
	"erickson.com":           1,
	"espinoza-johnson.com":   1,
	"evans-mullen.com":       1,
	"evans.com":              1,
	"fields-welch.com":       1,
	"fisher.com":             1,
	"flores.com":             1,
	"flynn.com":              1,
	"foster.com":             1,
	"frazier-chang.com":      1,
	"fuller.com":             1,
	"garcia-perez.com":       1,
	"gardner-taylor.com":     1,
	"gardner.com":            1,
	"gomez-shaw.com":         1,
	"gonzales-robertson.com": 1,
	"gonzalez.com":           1,
	"goodman.com":            1,
	"gordon.com":             1,
	"gutierrez.com":          1,
	"hale.com":               1,
	"hamilton-allen.com":     1,
	"hampton-brown.com":      1,
	"hardy.com":              1,
	"harrison.com":           1,
	"hartman.com":            1,
	"hayes-castro.com":       1,
	"hayes.com":              1,
	"henderson-fox.com":      1,
	"henry-jenkins.com":      1,
	"herrera-bentley.com":    1,
	"herrera.com":            1,
	"hinton.com":             1,
	"holland.com":            1,
	"hood.com":               1,
	"hopkins-martin.com":     1,
	"hunter.com":             1,
	"johnson-gonzalez.com":   1,
	"johnston.com":           1,
	"jones-jarvis.com":       1,
	"jones-ortega.com":       1,
	"jones-sosa.com":         1,
	"jones.com":              1,
	"jordan-higgins.com":     1,
	"jordan.com":             1,
	"keller.com":             1,
	"kelly.com":              1,
	"kemp.com":               1,
	"kim-brown.com":          1,
	"kim-jones.com":          1,
	"king.com":               1,
	"lang-pham.com":          1,
	"le-santiago.com":        1,
	"lee-lewis.com":          1,
	"lee-thomas.com":         1,
	"lester-barnes.com":      1,
	"lewis.com":              1,
	"little-becker.com":      1,
	"lloyd.com":              1,
	"lucas-mccall.com":       1,
	"lyons.com":              1,
	"manning.com":            1,
	"martin-mitchell.com":    1,
	"martin.com":             1,
	"martinez-martin.com":    1,
	"martinez-peterson.com":  1,
	"martinez.com":           1,
	"may.com":                1,
	"mayer.com":              1,
	"mcbride.com":            1,
	"mccormick.com":          1,
	"mccoy.com":              1,
	"mcgee.com":              1,
	"mckee.com":              1,
	"mckenzie.com":           1,
	"meadows-gross.com":      1,
	"michael.com":            1,
	"miller-evans.com":       1,
	"miller-stout.com":       1,
	"miller.com":             1,
	"mills-tapia.com":        1,
	"mills.com":              1,
	"mitchell.com":           1,
	"moon-taylor.com":        1,
	"moore.com":              1,
	"morgan-chavez.com":      1,
	"morris-bradshaw.com":    1,
	"morris-jones.com":       1,
	"munoz.com":              1,
	"murray-miller.com":      1,
	"nelson-williams.com":    1,
	"nichols-becker.com":     1,
	"norton-ruiz.com":        1,
	"nunez-matthews.com":     1,
	"ortega.com":             1,
	"ortiz.com":              1,
	"osborne-jones.com":      1,
	"osborne.com":            1,
	"page-shepherd.com":      1,
	"palmer.com":             1,
	"patel.com":              1,
	"payne-wilson.com":       1,
	"pena-clark.com":         1,
	"perkins-clark.com":      1,
	"perkins-jenkins.com":    1,
	"peters.com":             1,
	"peterson.com":           1,
	"phelps.com":             1,
	"pope.com":               1,
	"porter-fitzgerald.com":  1,
	"potter.com":             1,
	"proctor.com":            1,
	"ramos.com":              1,
	"rangel.com":             1,
	"reid.com":               1,
	"rhodes.com":             1,
	"rich-newman.com":        1,
	"richmond.com":           1,
	"rivera.com":             1,
	"robbins.com":            1,
	"roberson-scott.com":     1,
	"robinson-williams.com":  1,
	"rodriguez-hendrix.com":  1,
	"rodriguez-kerr.com":     1,
	"rogers-chavez.com":      1,
	"rojas.com":              1,
	"rose.com":               1,
	"ross.com":               1,
	"ryan-diaz.com":          1,
	"sanders-richardson.com": 1,
	"scott.com":              1,
	"shaw-castillo.com":      1,
	"shaw-rhodes.com":        1,
	"silva-jordan.com":       1,
	"small.com":              1,
	"smith-valencia.com":     1,
	"solis-white.com":        1,
	"solomon-anderson.com":   1,
	"soto-davis.com":         1,
	"soto.com":               1,
	"spencer-black.com":      1,
	"stephens.com":           1,
	"stevens.com":            1,
	"stewart-jones.com":      1,
	"strong-henderson.com":   1,
	"swanson.com":            1,
	"thomas-shea.com":        1,
	"thompson-dillon.com":    1,
	"thompson-jarvis.com":    1,
	"thompson-ortiz.com":     1,
	"thompson-russell.com":   1,
	"thornton-lozano.com":    1,
	"torres-mclean.com":      1,
	"vega.com":               1,
	"villarreal.com":         1,
	"wall.com":               1,
	"wallace-taylor.com":     1,
	"wallace.com":            1,
	"walter.com":             1,
	"walters-jimenez.com":    1,
	"wang-pacheco.com":       1,
	"waters.com":             1,
	"watkins.com":            1,
	"weiss.com":              1,
	"welch.com":              1,
	"west.com":               1,
	"white.com":              1,
	"whitehead-davidson.com": 1,
	"williams-tyler.com":     1,
	"williams.com":           1,
	"williamson.com":         1,
	"wilson-johnson.com":     1,
	"wise-gill.com":          1,
	"wood-hill.com":          1,
	"wright-anderson.com":    1,
	"wright.com":             1,
	"wu.com":                 1,
	"yang-cook.com":          1,
	"yoder-hall.com":         1,
	"yu.com":                 1,
	"zimmerman-boyle.com":    1,
}
