// Code generated by MockGen. DO NOT EDIT.
// Source: apps/lib/storage/event.go

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddEvent mocks base method.
func (m *MockStorage) AddEvent(event Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEvent indicates an expected call of AddEvent.
func (mr *MockStorageMockRecorder) AddEvent(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvent", reflect.TypeOf((*MockStorage)(nil).AddEvent), event)
}

// DeleteEvent mocks base method.
func (m *MockStorage) DeleteEvent(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockStorageMockRecorder) DeleteEvent(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockStorage)(nil).DeleteEvent), id)
}

// DeleteEventsOlderThan mocks base method.
func (m *MockStorage) DeleteEventsOlderThan(years, months, days int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEventsOlderThan", years, months, days)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEventsOlderThan indicates an expected call of DeleteEventsOlderThan.
func (mr *MockStorageMockRecorder) DeleteEventsOlderThan(years, months, days interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEventsOlderThan", reflect.TypeOf((*MockStorage)(nil).DeleteEventsOlderThan), years, months, days)
}

// ListEvents mocks base method.
func (m *MockStorage) ListEvents(arg0 time.Time, arg1 int) ([]Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1)
	ret0, _ := ret[0].([]Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockStorageMockRecorder) ListEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockStorage)(nil).ListEvents), arg0, arg1)
}

// ListEventsToNotify mocks base method.
func (m *MockStorage) ListEventsToNotify() ([]Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventsToNotify")
	ret0, _ := ret[0].([]Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventsToNotify indicates an expected call of ListEventsToNotify.
func (mr *MockStorageMockRecorder) ListEventsToNotify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventsToNotify", reflect.TypeOf((*MockStorage)(nil).ListEventsToNotify))
}

// MarkEventsNotificationSent mocks base method.
func (m *MockStorage) MarkEventsNotificationSent(ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventsNotificationSent", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEventsNotificationSent indicates an expected call of MarkEventsNotificationSent.
func (mr *MockStorageMockRecorder) MarkEventsNotificationSent(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventsNotificationSent", reflect.TypeOf((*MockStorage)(nil).MarkEventsNotificationSent), ids)
}

// UpdateEvent mocks base method.
func (m *MockStorage) UpdateEvent(event Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockStorageMockRecorder) UpdateEvent(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockStorage)(nil).UpdateEvent), event)
}
