services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    container_name: calendar_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d calendar"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    container_name: calendar_rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    image: thejubadze/calendar:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: calendar_app
